### ISSUE TITLE
invalid Manifest file

### ISSUE THREAD

**Issue by urpwnd** [League-of-Foundry-Developers/codemirror-lib#13]
CodeMirror's page on the official foundryvtt website, and using the manifest directly from github, both result in:

```
setup.js:292 Error: Unable to load valid world manifest data from "https://github.com/League-of-Foundry-Developers/codemirror-lib/releases/download/5.58.3-fvtt5/module.json"
World Model Validation Errors
[World.system]: may not be a blank string
[World.coreVersion]: may not be a blank string
    at Module.installPackage (/home/ubuntu/foundryvtt/resources/app/dist/packages/views.mjs:1:1620)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async SetupView.handlePost (/home/ubuntu/foundryvtt/resources/app/dist/server/views/setup.mjs:1:1980)
```

Additionally, CodeMirror doesn't show up in the installable list inside Foundry setup, but I suppose that might be on purpose. If so, nevermind! =)

Thanks for all you do.

**Comment by zeel01** [comment]
Should be fixed c2a18e07dd87756d0eacb497a296c5fa8e3b0de2
